<<<<<<< HEAD
name: CI/CD Pipeline to Production
=======
name: CI/CD Pipeline Production
>>>>>>> 48154188ac2aa21d2f7f0c0da5b43e9da8038573

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.14.0' # Ubah ke versi Node.js yang Anda gunakan

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

  deploy-to-production:
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.PRD_SERVER_SSH_KEY }}

    - name: Deploy to Development Server
      env:
        SERVER_IP: ${{ secrets.PRD_SERVER_IP }}
        SERVER_USERNAME: ${{ secrets.PRD_USERNAME}}
      run: |
        ssh $SERVER_USERNAME@$SERVER_IP 'cd ~/dev-momee && git pull && npm install && npx prisma migrate deploy && npm run build && pm2 restart dev-momee'

